# i3blocks config file
# Doc: http://vivien.github.io/i3blocks

# Global Param
separator=false
separator_block_width=15
markup=pango


# ─── CPU ──────────────────────────────────────────────
[CPU]
command=~/.config/i3blocks/cpu_useage.sh
interval=5
color=#00ff00

# ─── Mémoire ──────────────────────────────────────────────
[memory]
label=<span color="#FF0055">󰍛 </span>
command=free -h | awk '/^Mem:/ {print $3 "/" $2}'
interval=5
color=#ffffff

# ─── Disque ───────────────────────────────────────────────
[disk]
label=Disk 
command=df -h / | awk 'NR==2 {print $3 "/" $2 " (" $5 ")"}'
color=#3f26d1
interval=3600


# ─── Interface réseau (VPN) ───────────────────────────────
[iface]
label=<span color="#00FF41">󰇧 </span>
command=ip -4 addr show tun0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
color=#3BB92D
interval=120


# ─── Date & Heure ─────────────────────────────────────────
[time]
label=
command=echo "<span foreground='#C0CAF5'>$(date '+%H:%M')</span> <span foreground='#E0AF68'>$(date '+%A')</span>"
interval=1
